# Generated by Django 2.2.6 on 2019-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
